clean:
	del *exe
hw: 
	@g++ -Wall -Wextra -pedantic -std=c++11 -o homework -I ../include/ AlgoHomeWorkLinkList.cpp
	@./homework
T:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o T -I ../include/ SimpleListNodeTest.cpp
	@./T
hw2:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o hw1 -I ../include/ HomeWork01.cpp
	@./hw1

temp:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o TT -I ../include/ temp.cpp
	@./TT

4:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o h4 -I ../include/ 4HomeWork.cpp
	@./h4	

2:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o h2 -I ../include/ 2HomeWork.cpp
	@./h2	
all : clean  temp T hw2
