
hw: 
	@g++ -Wall -Wextra -pedantic -std=c++11 -o homework -I ../include/ AlgoHomeWorkLinkList.cpp
	@./homework
T:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o T -I ../include/ SimpleListNodeTest.cpp
	@./T
hw2:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o hw1 -I ../include/ HomeWork01.cpp
	@./hw1

temp:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o TT -I ../include/ temp.cpp
	@./TT