
hw: 
	@g++ -Wall -Wextra -pedantic -std=c++11 -o homework -I ../include/ AlgoHomeWorkLinkList.cpp
	@./homework
T:
	@g++ -Wall -Wextra -pedantic -std=c++11 -o T -I ../include/ SimpleListNodeTest.cpp
	@./T